version: '3'

services:
  # Frontend ReactJS
  react:
    build:
      context: ./film-frontend # Sesuaikan dengan lokasi folder frontend React
    ports:
      - "3000:3000"  # Port untuk akses aplikasi ReactJS
    volumes:
      - ./frontend:/app  # Mount folder lokal ke kontainer untuk memudahkan pengembangan
    depends_on:
      - laravel  # React akan menunggu backend Laravel siap
    environment:
      - REACT_APP_API_URL=http://laravel:8000  # Mengarah ke API Laravel

  # Backend Laravel
  laravel:
    build:
      context: ./film-backend  # Sesuaikan dengan lokasi folder backend Laravel
    ports:
      - "8000:80"  # Port untuk akses aplikasi Laravel
    volumes:
      - ./backend:/var/www  # Mount folder lokal ke kontainer
    depends_on:
      - postgres  # Laravel akan menunggu PostgreSQL siap
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=DramaKu  # Nama database PostgreSQL
      - DB_USERNAME=postgres  # Username untuk akses database
      - DB_PASSWORD=postgres  # Password untuk akses database

  # Database PostgreSQL
  postgres:
    image: postgres:16 # Menggunakan image PostgreSQL versi 13
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Volume untuk data persisten
    environment:
      - POSTGRES_USER=your_username  # Username untuk PostgreSQL
      - POSTGRES_PASSWORD=your_password  # Password untuk PostgreSQL
      - POSTGRES_DB=your_database  # Nama database untuk aplikasi Laravel
    ports:
      - "5432:5432"  # Port untuk akses database PostgreSQL

volumes:
  postgres-data:  # Volume untuk menyimpan data PostgreSQL secara persisten
